---
swagger: "2.0"
info:
  description: Chordata
  version: 1.0.0
  title: Chordata
host: virtserver.swaggerhub.com
basePath: /MarrickLip/Chordata/1.0.0
tags:
- name: datasets
  description: manage datasets
- name: developers
  description: Operations available to regular developers
schemes:
- https
paths:
  /datasets:
    get:
      tags:
      - datasets
      description: Test
      parameters: []
      responses:
        "200":
          description: a list of datasets
definitions: {}
