openapi: '3.0.2'
info:
  title: Chordata API
  version: '1.0'
  description: Backend API that powers the Chordata web app.

paths:
  /projects/:
    get:
      summary: List projects
      tags:
        - Projects
      responses:
        '200':
          description: OK
  /projects/{projectId}/:
    get:
      summary: Get a project
      tags:
        - Projects
      responses:
        200:
          description: OK
    put:
      summary: Create a new project
      tags:
        - Projects
      responses:
        200:
          description: OK
    patch:
      summary: Edit an existing project
      tags:
        - Projects
      responses:
        200:
          description: OK
    delete:
      summary: Delete a project
      tags:
        - Projects
      responses:
        200:
          description: OK
  /[Project]/deployments:
    get:
      summary: List deployments in a project
      tags:
        - Deployments
      responses:
        '200':
          description: OK
  /[Project]/deployments/{deploymentId}:
    get:
      summary: Get a deployment
      tags:
        - Deployments
      responses:
        200:
          description: OK
